### ISSUE TITLE
DataBaseHelper 및 Dijkstra, Nodes.db 수정 내용

### ISSUE THREAD

**Issue by Gnoyh** [kookmin-sw/capstone-2023-41#22]
DataBaseHelper에서 PlaceNode의 crossid 인자를 제거했습니다.
이유는 PlaceNode에서의 노드 id값과 CrossNode에서의 입구쪽 노드 id값을 같게 변경해서 굳이 crossid를 통해 입구쪽 노드 id값을 받아올 필요가 없이 자신의 id값을 그대로 findCrosstoID() 함수에 넣으면 CrossNode를 받아올 수 있기 때문입니다.

또한 Dijkstra에서 최종 return되는 List<Pair<i: Int, s: String>>에서 s가 동서남북중 하나일 경우에는 findCrosstoID() 함수를 통해 구한 i를 id값으로 하는 CrossNode의 이미지 중 동서남북에 맞게 출력하면 길찾기시 교차로에서 방향에 맞는 사진이 나오도록 구현하였고, s가 place인 경우에는 PlaceNode의 입구쪽 노드이므로 길찾기시 사진을 보여줄 필요가 없습니다. 또한 s가 start일 때는 i값이 시작 노드의 id, s가 end일 때는 i값이 도착 노드의 id가 되도록 구현하였습니다.

그리고 Nodes.db 파일의 이미지를 실제 미래관에서 찍은 사진으로 교체했습니다.

혹시 또 궁금하신 점 있으면 언제든 연락주세요!

**Comment by MarkSon-42** [comment]
상세 설명 감사합니다!!! 👍👍👍

**Comment by MarkSon-42** [comment]
Closed issue
